#' Plot difference of Simulated and Observed correlations
#'
#' @inheritParams SimuData
#' @param x SimuData dataset
#'
#' @export
plot.SimuData <- function(x, Corr = Cors, ...){
  dCors <- cor(as.matrix(x), method = 'spear') - Corr
  cat("\n Range of differences:", round(range(dCors,na.rm = T), 3), '\n')
  suppressWarnings(
    heatmap.2(dCors,
              Rowv=F, Colv=F,
              col = bluered,symm=T, trace="n",
              main='Difference of simulated and observed correlations'))
}

#' Plot heatmaps of simulated data
#'
#' @param x A MIMOmicsData object as generated by \code{\link{GenData}}.
#' @return NULL
#' @keywords internal
#' @export
plot.MIMOmicsData <- function(x, ...){
  with(x, {
    plot(SNP1, Cors)
    plot(SNP2, Cors2)
    suppressWarnings(heatmap.2(cor(X1[,-which(colSums(X1)==0)]), Rowv=F, Colv=F, col = bluered, breaks=seq(-1,1,length.out = 100),symm=T, trace="n",main='X1 corr w/o zero-sd IGPs'))
    suppressWarnings(heatmap.2(cor(X1m), Rowv=F, Colv=F, col = bluered, breaks=seq(-1,1,length.out = 100),symm=T, trace="n",main='X1m with all IGP'))
    suppressWarnings(heatmap.2(cor(X2), Rowv=F, Colv=F, col = bluered, breaks=seq(-1,1,length.out = 100),symm=T, trace="n",main='X2'))
    suppressWarnings(heatmap.2(cor(X2m), Rowv=F, Colv=F, col = bluered, breaks=seq(-1,1,length.out = 100),symm=T, trace="n",main='X2m'))
    if(ncol(X2m)>=100){
      suppressWarnings(heatmap.2(cor(X1m,X2m[,1:100]), Rowv=F, Colv=F, col = bluered, breaks=seq(-1,1,length.out = 100),symm=F, trace="n",main='Cor between X1m and X2m (first 100 variables)'))
    }
  })
}

#' Print RV coefs of simulated data
#'
#' @inheritParams plot.MIMOmicsData
#' @return NULL
#' @keywords internal
#' @export
print.MIMOmicsData <- function(x, digits = 3, ...){
  with(x, {
    cat("RV coeff between error free X1 and X2:", coeffRV(X1, X2) %>% round(digits),'\n')
    cat("RV coeff between noisy X1m and X2m:", coeffRV(X1m, X2m) %>% round(digits),'\n')
    cat("RV coeff between X1 and X1m:", coeffRV(X1, X1m) %>% round(digits),'\n')
    cat("RV coeff between X2 and X2m:", coeffRV(X2, X2m) %>% round(digits),'\n')
  })
}
